name: Docker build on PR
env:
        DOCKER_CLI_EXPERIMENTAL: enabled

on:
        pull_request:
                branches:
                  - master
                types: [opened, edited]

jobs:
        build:
                runs-on: ubuntu-18.04
                name: Build and push dashboard image
                steps:
                        - name: Set env variables
                          run: echo ::set-env name=PR_NUMBER::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
                        - name: Show set env variables
                          run: |
                                  printf "    PR_NUMBER: %s\n"  "$PR_NUMBER"                                  
                        - name: Login to Docker Hub
                          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                        - name: Checkout project
                          uses: actions/checkout@v2
                        - name: Setup Docker buildx action
                          uses: crazy-max/ghaction-docker-buildx@v1
                          id: buildx
                          with:
                                  buildx-version: latest
                                  qemu-version: latest
                        - name: Show available buildx platforms
                          run: echo ${{ steps.buildx.outputs.platforms }}
                        - name: Run Docker buildx against tag
                          run: |
                                  docker buildx build \
                                  --platform linux/amd64,linux/arm/v7 \
                                  -t ${{ secrets.DOCKER_HUB_USER }}/dashboard:pr-$PR_NUMBER \
                                  --output "type=registry" \
                                  .
                        - name: Run Docker buildx against stage
                          run: |
                                docker buildx build \
                                --platform linux/amd64 \
                                -f ./Dockerfile.stage \
                                -t ${{ secrets.DOCKER_HUB_USER }}/dashboard:pr-$PR_NUMBER \
                                --output "type=registry" \
                                .
