name: Docker build on master
env:
        DOCKER_CLI_EXPERIMENTAL: enabled

on:
        push:
                branches:
                  - master

jobs:
        build:
                runs-on: ubuntu-18.04
                name: Build and push dashboard image
                steps:                                
                        - name: Login to Docker Hub
                          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                        - name: Checkout project
                          uses: actions/checkout@v2
                        - name: Setup Docker buildx action
                          uses: crazy-max/ghaction-docker-buildx@v1
                          id: buildx
                          with:
                                  buildx-version: latest
                                  qemu-version: latest
                        - name: Show available buildx platforms
                          run: echo ${{ steps.buildx.outputs.platforms }}
                        - name: Run Docker buildx
                          run: |
                                  docker buildx build \
                                  --platform linux/amd64,linux/arm/v7 \
                                  -t ${{ secrets.DOCKER_HUB_USER }}/dashboard:master \
                                  --output "type=registry" \
                                  .
                        - name: Run Docker buildx against stage
                          run: |
                                docker buildx build \
                                --platform linux/amd64 \
                                -f ./Dockerfile.stage \
                                -t ${{ secrets.DOCKER_HUB_USER }}/dashboard:stage-master \
                                --output "type=registry" \
                                .
