name: Automatically Build image on tag
env:
        DOCKER_CLI_EXPERIMENTAL: enabled

on:
        push:
                tags: 
                  - v[0-9]+.[0-9]+.[0-9]+
                  - v[0-9]+.[0-9]+.[0-9]+-*

jobs:
        build:
                runs-on: ubuntu-latest
                name: Build / Push Umbrel Dashboard on version tag
                steps:
                  - run: echo $TAG